# Generated by Django 4.2.23 on 2025-08-07 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rfq.rfq'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('renter', 'merchant', 'rfq')},
        ),
    ]
