version : "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=false
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command:
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py seed_categories &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - .env/prod.env
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env/prod.env

volumes:
  dev-db-data: