# Generated by Django 4.2.23 on 2025-08-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Accepted', 'Accepted')], default='Open', max_length=15),
        ),
    ]
