# Generated by Django 4.2.23 on 2025-08-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_alter_rfq_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='notes_per_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
