# Generated by Django 4.2.23 on 2025-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_alter_rfq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
