# Generated by Django 4.2.23 on 2025-08-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0003_alter_rfq_notes_per_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='notes_per_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
