# Generated by Django 4.2.23 on 2025-08-25 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfq', '0003_rfq_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='saved',
        ),
        migrations.AddField(
            model_name='rfq',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_rfqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfq',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_rfqs', to=settings.AUTH_USER_MODEL),
        ),
    ]
