# Generated by Django 4.2.23 on 2025-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0004_alter_rfq_notes_per_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='public', max_length=10),
        ),
    ]
