# Generated by Django 4.2.7 on 2025-01-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_roles'),
        ('rfq', '0004_remove_rfq_saved_rfq_reported_by_rfq_saved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_comments', to='core.user')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rfq.rfq')),
            ],
        ),
    ]
