# Generated by Django 4.2.24 on 2025-09-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merchantprofile_is_verified'),
        ('rfq', '0005_rfqcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.merchantprofile'),
        ),
    ]
