# Generated by Django 4.2.24 on 2025-09-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0007_alter_rfq_created_by_alter_rfq_receiver'),
    ]

    operations = [
    ]
