# Generated by Django 4.2.24 on 2025-09-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0008_auto_20250925_0844'),
        ('core', '0007_alter_user_role_alter_user_username'),
    ]

    operations = [
        # First, remove the existing receiver field (which points to MerchantProfile)
        migrations.RemoveField(
            model_name='rfq',
            name='receiver',
        ),
        # Then add the new receiver field pointing to User
        migrations.AddField(
            model_name='rfq',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_rfqs', to='core.user'),
        ),
    ]
