# Generated by Django 4.2.23 on 2025-08-05 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_change_created_by_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcategory',
            name='style',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
