# Generated by Django 4.2.23 on 2025-08-05 02:33

from django.db import migrations, models

def populate_categories(apps, schema_editor):
    TrainingCategory = apps.get_model('training', 'TrainingCategory')
    
    categories_data = [
        {'name': 'Lighting', 'style': 'bg-blue-100 text-blue-800'},
        {'name': 'Camera Operation', 'style': 'bg-green-100 text-green-800'},
        {'name': 'Directing', 'style': 'bg-orange-100 text-orange-800'},
        {'name': 'Audio Recording', 'style': 'bg-purple-100 text-purple-800'},
        {'name': 'Post-Production', 'style': 'bg-red-100 text-red-800'},
        {'name': 'Grip & Electric', 'style': 'bg-yellow-100 text-yellow-800'},
    ]
    
    for category_data in categories_data:
        TrainingCategory.objects.get_or_create(
            name=category_data['name'],
            defaults={'style': category_data['style']}
        )

def reverse_populate_categories(apps, schema_editor):
    TrainingCategory = apps.get_model('training', 'TrainingCategory')
    TrainingCategory.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingcategory_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcategory',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(populate_categories, reverse_populate_categories),
    ]
