# Generated by Django 4.2.23 on 2025-07-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gear_hub.models
import user.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GearCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('equipment_name', models.CharField(max_length=100)),
                ('key_specifications', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('pick_up_location', models.JSONField(default=gear_hub.models.default_JSON)),
                ('location_privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('closed', 'Closed'), ('draft', 'Draft'), ('packaging_only', 'Packaging Only')], default='public', max_length=20)),
                ('rentals', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_gear_items', to=settings.AUTH_USER_MODEL)),
                ('equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear_hub.gearcategories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GearItemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=user.utils.get_gear_items_picture_path)),
                ('is_cover_photo', models.BooleanField(default=False)),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear_hub.gearitem')),
            ],
        ),
        migrations.CreateModel(
            name='AddFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear_hub.gearitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
