# Generated by Django 4.2.11 on 2024-03-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitem',
            name='rent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gearitem',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
