# Generated by Django 4.2.23 on 2025-07-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearcategories',
            name='item_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
