# Generated by Django 4.2.23 on 2025-07-24 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearcategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear_hub.gearcategories'),
        ),
    ]
