# Generated by Django 4.2.23 on 2025-07-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0002_gearcategories_item_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gearcategories',
            old_name='item_color',
            new_name='category_color',
        ),
    ]
