# Generated by Django 4.2.11 on 2024-03-20 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0002_alter_gearitem_rent_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearcategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gear_hub.gearcategories'),
        ),
    ]
