# Generated by Django 4.2.13 on 2024-07-11 17:56

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0003_alter_gearcategories_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearItemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=app.storage_backends.PublicMediaStorage, upload_to=user.utils.get_upload_path)),
                ('is_cover_photo', models.BooleanField(default=False)),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear_hub.gearitem')),
            ],
        ),
    ]
