# Generated by Django 4.2.14 on 2024-07-22 13:05

import app.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gear_hub', '0004_gearitempicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitempicture',
            name='image',
            field=models.ImageField(storage=app.storage_backends.PublicMediaStorage, upload_to=user.utils.get_gear_items_picture_path),
        ),
        migrations.CreateModel(
            name='AddFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear_hub.gearitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
