# Generated by Django 4.2.14 on 2024-07-30 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gear_hub', '0005_alter_gearitempicture_image_addfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='location_privacy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='promotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='rentals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='replacement_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='total_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='visibility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GearItemRent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('details', models.TextField()),
                ('included_accessories', models.JSONField(default=[])),
                ('daily_rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('blocked_dates', models.JSONField(default=[])),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear_hub.gearitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('pick_up', models.DateTimeField()),
                ('drop_off', models.DateTimeField()),
                ('total_days', models.IntegerField()),
                ('actual_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('is_confirm', models.BooleanField(default=False)),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear_hub.gearitem')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
