# Generated by Django 4.2.14 on 2024-07-31 11:09

from django.db import migrations, models
import gear_hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0006_gearitem_brand_gearitem_lat_gearitem_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitemrent',
            name='blocked_dates',
            field=models.JSONField(default=gear_hub.models.default_JSON),
        ),
        migrations.AlterField(
            model_name='gearitemrent',
            name='included_accessories',
            field=models.JSONField(default=gear_hub.models.default_JSON),
        ),
    ]
