# Generated by Django 4.2.14 on 2024-08-22 08:43

from django.db import migrations, models
import gear_hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearitem',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='gearitem',
            name='lng',
        ),
        migrations.AddField(
            model_name='gearitem',
            name='pick_up_location',
            field=models.JSONField(default=gear_hub.models.default_JSON),
        ),
    ]
