# Generated by Django 4.2.15 on 2024-09-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0009_remove_gearitem_lat_remove_gearitem_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lng',
            field=models.FloatField(),
        ),
    ]
