# Generated by Django 4.2.15 on 2024-09-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0010_alter_booking_lat_alter_booking_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitem',
            name='location_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('closed', 'Closed'), ('draft', 'Draft'), ('packaging_only', 'Packaging Only')], default='public', max_length=20),
        ),
    ]
