# Generated by Django 4.2.19 on 2025-02-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0012_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='drop_off',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='gear_item',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirm',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pick_up',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_days',
        ),
        migrations.AddField(
            model_name='booking',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear_hub.cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='drop_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='has_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='pick_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
