# Generated by Django 4.2.19 on 2025-02-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0013_remove_booking_actual_price_remove_booking_drop_off_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
