# Generated by Django 4.2.19 on 2025-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0014_rename_cart_id_booking_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('awaiting_confirmation', 'Awaiting Confirmation'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='awaiting_confirmation', max_length=30),
        ),
        migrations.AddField(
            model_name='gearitemrent',
            name='qty_rented',
            field=models.IntegerField(default=0),
        ),
    ]
