# Generated by Django 4.2.22 on 2025-07-06 09:32

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0016_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitempicture',
            name='image',
            field=models.ImageField(upload_to=user.utils.get_gear_items_picture_path),
        ),
    ]
