# Generated by Django 4.2.22 on 2025-07-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0017_alter_gearitempicture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gearitem',
            old_name='features',
            new_name='key_specifications',
        ),
        migrations.AddField(
            model_name='gearitem',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
