# Generated by Django 4.2.22 on 2025-07-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0018_rename_features_gearitem_key_specifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gearitem',
            old_name='key_specifications',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='gearitem',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='gearitem',
            name='is_public',
        ),
    ]
