# Generated by Django 4.2.22 on 2025-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_hub', '0019_rename_key_specifications_gearitem_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gearitem',
            old_name='category',
            new_name='equipment_category',
        ),
        migrations.RenameField(
            model_name='gearitem',
            old_name='name',
            new_name='equipment_name',
        ),
        migrations.RenameField(
            model_name='gearitem',
            old_name='features',
            new_name='key_specifications',
        ),
        migrations.RenameField(
            model_name='gearitem',
            old_name='provider',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='gearitem',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
