# Generated by Django 4.2.22 on 2025-07-07 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_merchantprofile_equipment_categories_and_more'),
        ('gear_hub', '0020_rename_category_gearitem_equipment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.merchantprofile'),
        ),
    ]
