# Generated by Django 4.2.10 on 2024-02-22 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_type', models.CharField(choices=[('photography_studios', 'Photography Studios'), ('production_companies', 'Production Companies'), ('event_planner', 'Event Planners'), ('marketing_agencies', 'Marketing Agencies'), ('educational_institutions', 'Educational Institutions'), ('freelance_photographers_and_videographers', 'Freelance Photographers and Videographers'), ('tourism_companies', 'Tourism Companies'), ('real_state_agencies', 'Real Estate Agencies'), ('corporate_businesses', 'Corporate Businesses'), ('non_profit_organizations', 'Non-Profit Organizations')], max_length=50)),
                ('organization_strength', models.CharField(choices=[('1-5', '1-5 members'), ('6-10', '6-10 members'), ('11-20', '11-20 members'), ('21-50', '21-50 members'), ('51-100', '51-100 members'), ('101-200', '101-200 members'), ('201-500', '201-500 members'), ('501_plus', '501+ members')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
