# Generated by Django 4.2.10 on 2024-03-06 10:50

from django.db import migrations, models
import user.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentityVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('document', models.FileField(upload_to=user.utils.get_upload_path)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('identity_card', 'Identity Card')], max_length=14)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
