# Generated by Django 4.2.23 on 2025-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='equipment_category',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='equipment_categories',
            field=models.ManyToManyField(blank=True, to='user.equipmentcategory'),
        ),
    ]
