# Generated by Django 4.2.24 on 2025-09-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_merchantprofile_equipment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
