# Generated by Django 4.2.10 on 2024-03-06 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_useridentityverification_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIdentityVerification',
            new_name='IdentityVerification',
        ),
    ]
