# Generated by Django 4.2.23 on 2025-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_merchantprofile_equipment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='equipment_categories',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='equipment_categories',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
