# Generated by Django 4.2.11 on 2024-03-13 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_rename_useridentityverification_identityverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=14)),
                ('profile_picture', models.ImageField(default='profile-photo/default.png', upload_to=user.utils.profile_picture_path)),
                ('cover_picture', models.ImageField(default='cover-photo/default.png', upload_to=user.utils.cover_picture_path)),
                ('dob', models.DateField(blank=True, null=True)),
                ('about', models.TextField(max_length=500)),
                ('address', models.TextField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
