# Generated by Django 4.2.23 on 2025-08-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_merchantprofile_equipment_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='pro_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
