# Generated by Django 4.2.11 on 2024-03-20 21:12

import app.storage_backends
from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='document',
            field=models.FileField(storage=app.storage_backends.PrivateMediaStorage, upload_to=user.utils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(default='cover-photo/default.png', storage=app.storage_backends.PublicMediaStorage, upload_to=user.utils.cover_picture_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile-photo/default.png', storage=app.storage_backends.PublicMediaStorage, upload_to=user.utils.profile_picture_path),
        ),
    ]
