# Generated by Django 4.2.23 on 2025-09-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merchantprofile_is_pro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
