# Generated by Django 4.2.15 on 2024-09-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
