# Generated by Django 4.2.22 on 2025-07-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_equipmentcategory_merchantprofile_renterprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='equipment_categories',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.equipmentcategory'),
        ),
    ]
