# Generated by Django 4.2.10 on 2024-02-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('gear_provider', 'Gear Provider')], default='renter', max_length=20),
        ),
    ]
