# Generated by Django 4.2.23 on 2025-08-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
