# Generated by Django 4.2.23 on 2025-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.TextField(blank=True),
        ),
    ]
