# Generated by Django 4.2.24 on 2025-09-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0005_rfqcomment'),
        ('message', '0002_message_sender_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='rfq_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.rfq'),
        ),
    ]
