# Generated by Django 4.2.24 on 2025-09-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_conversation_rfq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='rfq_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
