# Generated by Django 4.2.24 on 2025-09-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_attachment_message_alter_message_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='message',
        ),
    ]
